import React from 'react';
import { Execution } from '../../types/execution';
import { Repository } from '../../types/repository';
import { Card } from '../common/Card';
import { formatShortSha, formatTimeAgo } from '../../utils/formatters';
import { FileText, Sparkles, FolderGit2 } from 'lucide-react';

interface DocumentationUpdatesCardProps {
  executions: Execution[];
  repositories?: Repository[];
  onOpenDiff: (diff: string, title: string) => void;
}

export const DocumentationUpdatesCard: React.FC<DocumentationUpdatesCardProps> = ({
  executions,
  repositories = [],
  onOpenDiff,
}) => {
  // Collect all updated documents from completed executions
  const recentDocUpdates: Array<{
    exec: Execution;
    repoName: string;
    docPath: string;
    summary: string;
    diff: string;
  }> = [];

  executions.forEach((exec) => {
    const repo = repositories.find((r) => r.id === exec.repository_id);
    const repoDisplayName = repo?.name || exec.repository_name || 'Repository';

    exec.updated_documents?.forEach((doc) => {
      recentDocUpdates.push({
        exec,
        repoName: repoDisplayName,
        docPath: doc.doc_path,
        summary: doc.summary_of_changes,
        diff: doc.diff || exec.generated_diff || '',
      });
    });
  });

  return (
    <Card className="p-0 overflow-hidden bg-white dark:bg-[#0D1526] border border-stone-200/90 dark:border-slate-800/90 shadow-xs">
      <div className="p-5 border-b border-stone-100 dark:border-slate-800 bg-[#F7F5F0] dark:bg-[#131D2E]">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Recent Documentation Updates</h3>
        </div>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
          Autonomous documentation diffs generated by Agent 3
        </p>
      </div>

      <div className="divide-y divide-stone-100 dark:divide-slate-800/80">
        {recentDocUpdates.length === 0 ? (
          <div className="p-8 text-center text-slate-500 dark:text-slate-400 italic text-sm">
            No documentation updates generated yet.
          </div>
        ) : (
          recentDocUpdates.slice(0, 4).map((item, i) => (
            <div
              key={i}
              onClick={() => onOpenDiff(item.diff, `Diff: ${item.docPath} (${item.repoName} @ ${formatShortSha(item.exec.commit_sha)})`)}
              className="p-4 hover:bg-stone-50/80 dark:hover:bg-slate-800/40 transition-colors cursor-pointer group"
            >
              <div className="flex flex-wrap items-center justify-between gap-2 mb-1.5">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 text-[11px] font-mono font-semibold px-2 py-0.5 rounded-md bg-[#F7F5F0] dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-stone-200 dark:border-slate-700">
                    <FolderGit2 className="w-3 h-3 text-slate-600 dark:text-slate-400" />
                    {item.repoName}
                  </span>
                  <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-emerald-800 dark:text-emerald-300">
                    <FileText className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                    <span>{item.docPath}</span>
                  </div>
                </div>
                <span className="text-[11px] font-mono text-slate-500 dark:text-slate-400">
                  {formatTimeAgo(item.exec.created_at)}
                </span>
              </div>

              <p className="text-xs text-slate-700 dark:text-slate-300 line-clamp-2 leading-relaxed group-hover:text-slate-900 dark:group-hover:text-slate-100">
                {item.summary}
              </p>

              <div className="flex items-center justify-between mt-2 pt-2 border-t border-stone-100 dark:border-slate-800 text-[11px] text-slate-500 dark:text-slate-400 font-mono">
                <span>Commit {formatShortSha(item.exec.commit_sha)}</span>
                <span className="text-emerald-700 dark:text-emerald-400 font-semibold hover:underline">View Diff →</span>
              </div>
            </div>
          ))
        )}
      </div>
    </Card>
  );
};

